### ISSUE TITLE
cluster.yml - 'dict object' has no attribute 'nodename'

### ISSUE THREAD

**Issue by PC-Admin** [stackhpc/ansible-collection-cephadm#155]
This is a common one I see when attempting to first bootstrap a cluster with this collection, and template the main cluster.yml spec...
```
TASK [stackhpc.cephadm.cephadm : Template out cluster.yml] *************************************************************************************************************
fatal: [storage-13-09002]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'nodename'"}
```

It's this task in question: https://github.com/stackhpc/ansible-collection-cephadm/blob/fc73a5d7a5adbef20d9f044a92ab5dff674d8607/roles/cephadm/tasks/bootstrap.yml#L76

Which seems to refer to this (missing?) ansible fact:
https://github.com/stackhpc/ansible-collection-cephadm/blob/fc73a5d7a5adbef20d9f044a92ab5dff674d8607/roles/cephadm/templates/cluster.yml.j2#L4

Strangely this variable is definitely defined before the bootstrap role is called:
```
TASK [cephadm-setup : DEBUG - Display nodename] ***************************************************************************************************************************************
...
ok: [storage-13-09002] => {
    "ansible_facts.nodename": "storage-13-09002"
}
ok: [storage-13-09004] => {
    "ansible_facts.nodename": "storage-13-09004"
}
ok: [storage-13-09006] => {
    "ansible_facts.nodename": "storage-13-09006"
}
```

This bug seems to occur consistently either on the first run, or if `-e cephadm_bootstrap=true` is set. Otherwise it doesn't occur.

Happy to provide more context if needed.

**Comment by PC-Admin** [comment]
This might be a non-issue that's actually being caused by me having a few expected hosts down during bootstrap, I'll keep an eye on it...

**Comment by PC-Admin** [comment]
Yeah after putting this task before bootstrap I haven't seen this issue since:
```
- name: "If any host has failed execution, stop the playbook entirely."
  ansible.builtin.fail:
    msg: "Host {{ item }} has dropped from execution. Please ensure all hosts remain online during playbook run."
  when: item not in ansible_play_hosts
  with_items: "{{ groups['ceph'] }}"
  run_once: true
```

So it seems like yes, this is caused by having bootstrap not running against all the hosts in 'ceph' group. Closing this issue for now as it seems out of scope for this collection. Hopefully this issue is helpful for the next person who runs into this.
