### ISSUE TITLE
ec_profiles role doesn't support setting crush-failure-domain?

### ISSUE THREAD

**Issue by PC-Admin** [stackhpc/ansible-collection-cephadm#158]
So with this configuration my aim was to have a EC profile with OSDs as the failure domain. (As this is for a tiny 3x host testing cluster.)
```
cephadm_crush_rules:
  - name: replicated_nvme
    bucket_root: default
    bucket_type: osd
    device_class: nvme
    rule_type: replicated
  - name: ec42-osd
    rule_type: erasure
    bucket_type: osd
    profile: k4m2

cephadm_ec_profiles:
  - name: k4m2
    k: 4
    m: 2
```

Although when deployed, this doesn't seem to work as the underlying EC profile is still defaulting to 'hosts' for it's failure domain:
```
mcollins1@storage-14-09034:~$ sudo ceph osd erasure-code-profile ls
default
k4m2
mcollins1@storage-14-09034:~$ sudo ceph osd erasure-code-profile get k4m2
crush-device-class=
crush-failure-domain=host
crush-root=default
jerasure-per-chunk-alignment=false
k=4
m=2
plugin=jerasure
technique=reed_sol_van
w=8
```

When examining that role, there doesn't seem to be a field to actually set the failure domain at this level: https://github.com/stackhpc/ansible-collection-cephadm/blob/master/roles/ec_profiles/tasks/main.yml

I'm just manually creating the EC profile at the moment like so:
```
mcollins1@storage-14-09034:~$ sudo ceph osd erasure-code-profile set k4m2-osd plugin=jerasure technique=reed_sol_van k=4 m=2 crush-failure-domain=osd crush-device-class= crush-root=default w=8 jerasure-per-chunk-alignment=false
```

It would be nice though if we could set EC failure domains using this playbook.
